# Generated by Django 5.2.3 on 2025-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='isbn',
            field=models.CharField(unique=True),
        ),
    ]
