# Generated by Django 5.2.4 on 2025-08-27 08:32

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20250827_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Embedding vectoriel 1536 dimensions (text-embedding-ada-002)', size=1536)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', help_text="Nom du modèle utilisé pour générer l'embedding", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='collection.volume')),
            ],
            options={
                'verbose_name': 'Volume Embedding',
                'verbose_name_plural': 'Volume Embeddings',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['volume'], name='collection__volume__bbed87_idx'), models.Index(fields=['created_at'], name='collection__created_c4bde2_idx')],
            },
        ),
    ]
