# Generated by Django 5.2.3 on 2025-08-07 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_volume_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='authors',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.authors')),
                ('id_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.jobs')),
                ('id_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.serie')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['id'],
            },
        ),
    ]
