# Generated by Django 5.2.5 on 2025-08-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_volumeembedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolumeEmbedding',
        ),
    ]
