# Generated by Django 5.2.4 on 2025-08-26 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_read_read', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_read_volume', to='collection.volume')),
            ],
            options={
                'verbose_name': 'Read',
                'verbose_name_plural': 'Reads',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'volume')},
            },
        ),
    ]
